#!/usr/bin/python3
#MISE description="Create thumbnails of all JPG images in the Attachments directory"

# WARNING: This assumes the very specific original file size of 4000x3000 pixels, which
# is the default on my phone.
#
# This script will convert all JPG images in the Attachments directory to webp format.
# Only images that lie in their own sub-directory will be converted.
# The name of the subdirectory is used as the output file name.
#
# The conversion will crop the image file size to below 500kB, and then resize it to
# 4000x2000 pixels, assuming an original size of 4000x3000 pixels. The output will be
# saved in the same directory as the original image with a .webp extension.
#
# E.g.:
#     src/Attachments/mmm-delicious-dish/IMG_20210701_123456.jpg
# will be converted to
#     src/Attachments/mmm-delicious-dish/mmm-delicious-dish.webp
#
# The two commands are
#     cwebp -size 500000 "$1" -o "$2"
#     cwebp -crop 0 500 4000 2000 "$1" -o "$2"

import pathlib
import subprocess


def check_if_appropriate(i: pathlib.Path) -> pathlib.Path:
    parts = i.parts
    # Check if the image is in the Attachments directory
    if len(parts) < 3 or parts[1] != "Attachments":
        return pathlib.Path("none")
    # Skip if the file is directly in Attachments (not in a subdirectory)
    if parts[2] == parts[-1]:
        return pathlib.Path("none")
    else:
        name = parts[2]
    outname = i.parent / f"{name}.webp"
    return pathlib.Path("none") if outname.exists() else outname


def do_conversion(i: pathlib.Path, name: pathlib.Path) -> None:
    """Convert the image to be suitable as a thumbnail."""
    mise_run = ["mise", "exec", "npm:cwebp@latest", "--"]
    subprocess.run(mise_run + ["cwebp", "-size", "500000", i, "-o", name])
    subprocess.run(
        mise_run + ["cwebp", "-crop", "0", "500", "4000", "2000", name, "-o", name]
    )


def main() -> None:
    out = pathlib.Path().rglob("*.[Jj][Pp][Gg]")
    for i in out:
        print(f"Found {i}", end="")
        if (name := check_if_appropriate(i)).name != "none":
            print(". Converting...")
            do_conversion(i, name)
        else:
            print(", but it has already been converted.")


if __name__ == "__main__":
    main()
